### ISSUE TITLE
Fix error message

### ISSUE THREAD

**Issue by rohrlich** [emer/grunt#1]
Message should not say "and checked into git".

Also, I believe I got these errors because the way I passed args failed -- suggest adding an example to doc.

grund command: update in: active/roh000009/audonly at: 2019-12-22 16:45:07 UTC
Error: grunter.py script not found -- MUST be present and checked into git!

grund command: update in: active/roh000010/audonly at: 2019-12-22 16:45:07 UTC
Error: grunter.py script not found -- MUST be present and checked into git!

**Comment by rcoreilly** [comment]
how did you pass your args?  the args should be pretty standard..  I fixed the message

**Comment by rohrlich** [comment]
The first try was:
grunt submit --trials=5 --epochs=1 -m "whatever" 

and the second was:
grunt submit "--trials=5 --epochs=1" -m "whatever" 

when those trys didn't work I edited the grunter.py and put them after the --nogui

**Comment by rcoreilly** [comment]
after multiple bugs fixed (especially with python, if you don't test every path, there are likely to be bugs!), it is now working for me -- all fixes in grunt.py

**Comment by rcoreilly** [comment]
please close once it is working for you..

**Comment by rohrlich** [comment]
Working.
