### ISSUE TITLE
Grunti crash nuking 4 contiguously selected jobs

### ISSUE THREAD

**Issue by rohrlich** [emer/grunt#10]

**Comment by rohrlich** [comment]
rohrlich@MacBook-Pro-5:wordseg:> panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4e2d982]

goroutine 75 [running]:
github.com/go-gl/glfw/v3.3/glfw.(*Window).GetPos.func1(0x0, 0xc00feafaa8, 0xc00feafaac)
	/Users/rohrlich/go/src/github.com/go-gl/glfw/v3.3/glfw/window.go:452 +0x22
github.com/go-gl/glfw/v3.3/glfw.(*Window).GetPos(0x0, 0x4e462fd, 0xc000602eb0)
	/Users/rohrlich/go/src/github.com/go-gl/glfw/v3.3/glfw/window.go:452 +0x72
github.com/goki/gi/oswin/driver/glos.(*windowImpl).Position(0xc000602d80, 0x0, 0x0)
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/glos/window.go:376 +0x7e
github.com/goki/gi/gi.(*WindowGeomPrefs).RecordPref(0x68565c8, 0xc00fe96000)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/wingeom.go:251 +0x26e
github.com/goki/gi/gi.(*Window).HiPriorityEvents(0xc00fe96000, 0x542aba0, 0xc01607e040, 0x1)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/window.go:1686 +0x35b
github.com/goki/gi/gi.(*Window).ProcessEvent(0xc00fe96000, 0x542aba0, 0xc01607e040)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/window.go:1517 +0x3ec
github.com/goki/gi/gi.(*Window).EventLoop(0xc00fe96000)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/window.go:1456 +0x36
created by github.com/goki/gi/gi.(*Window).GoStartEventLoop
	/Users/rohrlich/go/src/github.com/goki/gi/gi/window.go:863 +0xa6

**Comment by rohrlich** [comment]
On restarting grunti the four jobs selected for nuke before the crash now show up in active as pending!

**Comment by rohrlich** [comment]
Important note -- these were old "done" jobs, not running jobs.

**Comment by rcoreilly** [comment]
looks like a window was moved and then died somehow.  I added a guard in the critical call there -- should prevent in the future.. closing for now -- re-report if you see it again after updating gogi.
