### ISSUE TITLE
Grunti -- Open is not reliable

### ISSUE THREAD

**Issue by rohrlich** [emer/grunt#12]
The results are in grunt/.../results/active... but sometimes selecting the job from the Done table and using Open doesn't work.

**Comment by rohrlich** [comment]
Ah, maybe when it is the last row!

**Comment by rcoreilly** [comment]
I couldn't replicate -- clicked on last row of Done and did Open and it opened..

**Comment by rohrlich** [comment]
Yeah, not a last row problem. I'll see if I can determine the conditions.

**Comment by rohrlich** [comment]
So it seems that the problem is not with open but with pull (not a grunti issue). Just leave open for now.

**Comment by rohrlich** [comment]
Closing

**Comment by rohrlich** [comment]
I finally noticed the cause. Sometimes the results are in grunt/wc/... locally but the link from projectdir/gresults to the local git has not been made and grunti "open" is looking in gresults.
