### ISSUE TITLE
Would like to be able to edit message after submit

### ISSUE THREAD

**Issue by rohrlich** [emer/grunt#15]
I sometimes :) find I have an error in my submit message. I think I had actually this capability myself in our svn version.

**Comment by rcoreilly** [comment]
will add at some point soon.  meanwhile, you can go to the local ~/grunt/wc.. etc dir for the job, edit job.message, and do git push.

**Comment by rcoreilly** [comment]
done -- grunt message at command line, and more convenient Message in grunti that gives you existing message to edit.
