### ISSUE TITLE
Git corrupted

### ISSUE THREAD

**Issue by rohrlich** [emer/grunt#17]
my wordseg project in grunt became unusable and I was not able to repair it. I created wordsegII and that is giving me grief now also. See grunti and nohup output. Below that is output from the ps command and attached is a piece of the nohup file from the time I was trying to repair my wordseg project.

grunti output:

exit status 1
Traceback (most recent call last):
  File "/usr/local/bin/grunt", line 735, in <module>
    write_cmd(grunt_jobid, cmd, timestamp())
  File "/usr/local/bin/grunt", line 254, in write_cmd
    with open(cmdfn,"w") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/rohrlich/grunt/wc/blanca/rohrlich/wordsegII/jobs/active/wordsegII/grcmd.results'
------------------------------------------------------

From nohup:

grund command: status in: active/roh000006/wordsegII at: 2020-10-16 15:55:55 UTC
Calling grunter for job: active/roh000006/wordsegII cmd: status
slurm_load_jobs error: Invalid job id specified
slurm id to stat:  10171671
Failed to stat job
status: NOTFOUND

grund command: status in: active/roh000007/wordsegII at: 2020-10-16 15:55:56 UTC
Calling grunter for job: active/roh000007/wordsegII cmd: status
slurm id to stat:  10171673
status: RUNNING

grund command: status in: active/roh000008/wordsegII at: 2020-10-16 15:55:56 UTC
Calling grunter for job: active/roh000008/wordsegII cmd: status
slurm_load_jobs error: Invalid job id specified
slurm id to stat:  10171674
Failed to stat job
status: NOTFOUND

----------------------------------------------
I always see the wordsegOldWiring project in the process list though I haven't been running jobs there for days.
[tmp.txt](https://github.com/emer/grunt/files/5392976/tmp.txt)

rohrlicj 15737  1.2  0.0 272320 15924 ?        Sl   10:07   0:00 python3 ./grund_sub.py /home/rohrlicj/grunt/wc/blanca/rohrlicj/wordsegOldWiring
rohrlicj 15756  0.0  0.0  14696  1444 ?        S    10:08   0:00 git pull -v origin
rohrlicj 15760  0.0  0.0  14696  1696 ?        S    10:08   0:00 /curc/sw/git/2.23.0/libexec/git-core/git fetch --update-head-ok -v origin
rohrlicj 15765  0.0  0.0  13760  1460 ?        S    10:08   0:00 git-upload-pack /home/rohrlicj/grunt/bb/blanca/rohrlicj/wordsegOldWiring/jobs
rohrlicj 15794  2.0  0.0 165712  2068 pts/13   R+   10:08   0:00 ps aux
rohrlicj 15795  0.1  0.0 112716   992 pts/13   S+   10:08   0:00 grep --color=auto rohr
rohrlicj 15812  0.0  0.0  13676  1168 ?        S    10:08   0:00 /curc/sw/git/2.23.0/libexec/git-core/git rev-list --objects --stdin --not --all --quiet --alternate-refs
root     19583  0.0  0.0 177272  5668 ?        Ss   Oct15   0:00 sshd: rohrlicj [priv]
rohrlicj 20778  0.0  0.0 178384  3720 ?        S    Oct15   0:06 sshd: rohrlicj@pts/13
rohrlicj 20790  0.0  0.0 125972  2336 pts/13   Ss   Oct15   0:00 -bash
rohrlicj 37149  0.0  0.0 195676 15704 ?        S    Oct14   0:30 python3 grund.py

**Comment by rcoreilly** [comment]
I do think the slowness of blanca is a problem.  the advantage of grunt is that *everything* is just based on git so you should be able to clean things up at the git level to recover from anything.  just kill the daemon, go into the wc repo (either on laptop or blanca -- make sure that both are pushed successfully first, then do any cleanup on either one (probably laptop) then push from there, then pull on blanca). 

you just have to go through the job directories and nuke anything that is corrupted etc.  manually scancel any running jobs!  etc.  there is no reason to abandon anything and it shouldn't be that hard to fix issues manually.

the new cluster should be up soon(ish) -- maybe a month or two unfortunately -- and then we can say goodbye to this absurd filesystem forever!
