### ISSUE TITLE
Grunti - A frequent crash with I believe a common stack trace

### ISSUE THREAD

**Issue by rohrlich** [emer/grunt#19]
rohrlich@MacBook-Pro-5:wordseg:> panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x6d8 pc=0x4e5cc91]

goroutine 127 [running]:
main.(*Grunt).OpenResults(0x6879400, 0xc00043b760, 0x4, 0x517f8e3, 0x4)
	/Users/rohrlich/go/src/github.com/emer/grunt/grunti/grunti.go:253 +0x91
reflect.Value.call(0x50d6920, 0x6879400, 0x4213, 0x517fbbf, 0x4, 0xc01da3c090, 0x2, 0x2, 0x54bcd80, 0xc01528d700, ...)
	/usr/local/go/src/reflect/value.go:460 +0x8ab
reflect.Value.Call(0x50d6920, 0x6879400, 0x4213, 0xc01da3c090, 0x2, 0x2, 0x0, 0x0, 0xc0005dd950)
	/usr/local/go/src/reflect/value.go:321 +0xb4
github.com/goki/gi/giv.MethViewCallMeth(0xc0047ea360, 0xc01da3c090, 0x2, 0x2)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/methview.go:734 +0x7d
github.com/goki/gi/giv.MethViewCall.func2(0x54923e0, 0xc000524000, 0x548c500, 0xc007764a80, 0x3, 0x0, 0x0)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/methview.go:704 +0x5a
github.com/goki/ki/ki.(*Signal).Emit(0xc007765468, 0x548c500, 0xc007764a80, 0x3, 0x0, 0x0)
	/Users/rohrlich/go/src/github.com/goki/ki/ki/signal.go:173 +0x1a7
github.com/goki/gi/gi.(*Dialog).Accept(0xc007764a80)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/dialogs.go:227 +0xe3
github.com/goki/gi/gi.(*Dialog).StdButtonConnect.func1(0x548c500, 0xc007764a80, 0x548ac40, 0xc0083da000, 0x0, 0x0, 0x0)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/dialogs.go:401 +0x83
github.com/goki/ki/ki.(*Signal).Emit(0xc0083db898, 0x548ac40, 0xc0083da000, 0x0, 0x0, 0x0)
	/Users/rohrlich/go/src/github.com/goki/ki/ki/signal.go:173 +0x1a7
github.com/goki/gi/gi.(*ButtonBase).BaseButtonRelease(0xc0083da000)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/buttons.go:328 +0x100
github.com/goki/gi/gi.(*ButtonBase).ButtonRelease(0xc0083da000)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/buttons.go:574 +0x2b
github.com/goki/gi/gi.(*ButtonBase).MouseEvent.func1(0x548ac40, 0xc0083da000, 0x5492c20, 0xc0083e8000, 0x0, 0x50986e0, 0xc008f37640)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/buttons.go:454 +0xd5
github.com/goki/gi/gi.(*WinEventRecv).Call(0xc0005dddb8, 0x5492c20, 0xc0083e8000, 0x0, 0x50986e0, 0xc008f37640)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/events.go:116 +0x8c
github.com/goki/gi/gi.(*EventMgr).SendEventSignal(0xc0083e8198, 0x543d380, 0xc008f37640, 0x1)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/events.go:225 +0x39a
github.com/goki/gi/gi.(*Window).ProcessEvent(0xc0083e8000, 0x543d380, 0xc008f37640)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/window.go:1547 +0x8d1
github.com/goki/gi/gi.(*Window).EventLoop(0xc0083e8000)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/window.go:1469 +0x36
created by github.com/goki/gi/gi.(*Window).GoStartEventLoop
	/Users/rohrlich/go/src/github.com/goki/gi/gi/window.go:876 +0xa6

[3]+  Exit 2                  grunti

**Comment by rcoreilly** [comment]
looks like no active view -- added a basic nil check -- definitely file others if this isn't fixed
