### ISSUE TITLE
Results for active also updating all of done jobs - 

### ISSUE THREAD

**Issue by rohrlich** [emer/grunt#21]
This is a lot of wasted time

**Comment by rcoreilly** [comment]
found the cause and fixed it: it was looking for a file named grcmd.update but that was now renamed to grcmd.results -- should be a lot faster now!

also I was having issues with running results on a specific job not making the link so open silently failed -- now always makes link.  I should probably add the error message too..

**Comment by rohrlich** [comment]
Yep, much better! Thanks.
