### ISSUE TITLE
nohup ... restart -- not restarting

### ISSUE THREAD

**Issue by rohrlich** [emer/grunt#3]
My experience with "nohup python3 grund.py restart &" is that the lock file is deleted but grund.py does not start.

**Comment by rcoreilly** [comment]
yes restart is more like "reset" and then you need to start it after that..

**Comment by rohrlich** [comment]
Ok if I edit the README to be clear on that point?

**Comment by rcoreilly** [comment]
yep

**Comment by rohrlich** [comment]
Hopefully clearer now.
