### ISSUE TITLE
Scroll select issue - returning to panel does not reset scroll position

### ISSUE THREAD

**Issue by rohrlich** [emer/grunt#33]
Only happens if you have enough rows in "done" table (probably any table) that you need a scroll bar.

1 - click on done panel tab and scroll down
2 - select any row
3 - "open" the results
4 - return to done panel
5- selected row is not the row you selected

**Comment by rcoreilly** [comment]
The problem does *not* occur if you select another tab before going back to done panel, or switching between panels in general -- it is something rather mysterious about the Open command..

**Comment by rcoreilly** [comment]
it is all due to this one function call on line 327 of grunti.go:
```go
	gr.TabView.SelectTabByName("Results")
```

**Comment by rcoreilly** [comment]
was a tiny typo in tableview -- initial render was using `ri` instead of `si`.
