### ISSUE TITLE
Sort lost after updates

### ISSUE THREAD

**Issue by rohrlich** [emer/grunt#39]

**Comment by rcoreilly** [comment]
can you provide a bit more info?

**Comment by rohrlich** [comment]
For example, list "done" jobs. Sort on any attribute. Pull, edit a message, anything that will update the done list.

I fixed this myself in the svn version by saving the sort and resorting after the update.

low priority

**Comment by rcoreilly** [comment]
now fixed in etview source -- much more robust overall..
