### ISSUE TITLE
grunt jobs n..N ignores n..N and shows all running jobs and no done jobs

### ISSUE THREAD

**Issue by rohrlich** [emer/grunt#8]

**Comment by rcoreilly** [comment]
yeah it probably doesn't parse job range.  just shows all jobs.  interprets args in wrong way.

**Comment by rohrlich** [comment]
shows all jobs if you don't specify range but if you do just the running.

**Comment by rcoreilly** [comment]
easy to change behavior in grunt.py..

**Comment by rcoreilly** [comment]
as help shows, the args are the type of jobs, not job numbers to list.  now it has archive and delete options too.

in any case, this is probably mitigated by grunti, so I'm going to close -- feel free to reopen if you think it is still needed.
