### ISSUE TITLE
Grunti crash clicking status with no rows in table

### ISSUE THREAD

**Issue by rohrlich** [emer/grunt#9]
rohrlich@MacBook-Pro-5:wordseg:> ./grunti
panic: runtime error: index out of range [0] with length 0

goroutine 5 [running]:
main.(*Grunt).SelectedJobs(0x685e300, 0x41d000004146c000, 0x716000045480000, 0xffffffffffffffff, 0x0)
	/Users/rohrlich/go/src/github.com/emer/grunt/grunti/grunti.go:437 +0x262
main.(*Grunt).Status(0x685e300)
	/Users/rohrlich/go/src/github.com/emer/grunt/grunti/grunti.go:222 +0x30
main.(*Grunt).Config.func3(0x5480080, 0xc000b4a000, 0x5477c80, 0xc00dfa6600, 0x0, 0x0, 0x0)
	/Users/rohrlich/go/src/github.com/emer/grunt/grunti/grunti.go:567 +0x33
github.com/goki/ki/ki.(*Signal).Emit(0xc00dfa7ef0, 0x5477c80, 0xc00dfa6600, 0x0, 0x0, 0x0)
	/Users/rohrlich/go/src/github.com/goki/ki/ki/signal.go:173 +0x1a7
github.com/goki/gi/gi.(*Action).ButtonRelease(0xc00dfa6600)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/action.go:222 +0x112
github.com/goki/gi/gi.(*ButtonBase).MouseEvent.func1(0x5477c80, 0xc00dfa6600, 0x5480080, 0xc000b4a000, 0x0, 0x5088ee0, 0xc0098d56c0)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/buttons.go:454 +0
github.com/goki/gi/gi.(*WinEventRecv).Call(0xc0010c5d28, 0x5480080, 0xc000b4a000, 0x0, 0x5088ee0, 0xc0098d56c0)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/events.go:116 +0x8c
github.com/goki/gi/gi.(*EventMgr).SendEventSignal(0xc000b4a198, 0x542a9a0, 0xc0098d56c0, 0x1)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/events.go:225 +0x39a
github.com/goki/gi/gi.(*Window).ProcessEvent(0xc000b4a000, 0x542a9a0, 0xc0098d56c0)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/window.go:1534 +0x8d1
github.com/goki/gi/gi.(*Window).EventLoop(0xc000b4a000)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/window.go:1456 +0x36
github.com/goki/gi/gi.(*Window).StartEventLoop(0xc000b4a000)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/window.go:854 +0x6d
main.guirun()
	/Users/rohrlich/go/src/github.com/emer/grunt/grunti/grunti.go:37 +0x3b
main.main.func1()
	/Users/rohrlich/go/src/github.com/emer/grunt/grunti/grunti.go:31 +0x20
github.com/goki/gi/gimain.Main.func1(0x543e3a0, 0x68280a0)
	/Users/rohrlich/go/src/github.com/goki/gi/gimain/gimain.go:31 +0x24
github.com/goki/gi/oswin/driver/glos.Main.func1()
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/glos/app.go:87 +0x40
created by github.com/goki/gi/oswin/driver/glos.Main
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/glos/app.go:86 +0x87

**Comment by rcoreilly** [comment]
not sure what caused that but I added guards.  reopen if happens again.
